SHOW DATABASES ;
CREATE DATABASE ashish_chatapp ;
USE ashish_chatapp ;

CREATE TABLE `rooms` (
`room_id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`room_name` VARCHAR(255) NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM rooms ;
DROP TABLE rooms ;

CREATE TABLE `room_members` (
`members_id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`user_id` BIGINT UNSIGNED NOT NULL,
`room_id` BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (`user_id`) REFERENCES `app_users`(`userID`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`room_id`) REFERENCES `rooms`(`room_id`) ON DELETE CASCADE ON UPDATE CASCADE
);
SELECT * FROM room_members ;
DROP TABLE room_members ;

CREATE TABLE room_messages (
  message_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NOT NULL,
  msg VARCHAR(255),
  sender_user_id BIGINT UNSIGNED NOT NULL,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (sender_user_id) REFERENCES app_users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);
SELECT * FROM room_messages ;
DROP TABLE room_messages ;
